### PR TITLE
added cookie and consent for user #46 

### LINKED ISSUE #46: ADD Cookie-control and consent for users
ADD Cookie and consent for users

a simple, functional banner works for now

### PR DESCRIPTION
**Pull request by devvsakib**
### Changes Made
Implemented a cookie consent banner using the `js-cookie` library to manage user consent for cookies on the website.

### Details
- Created a `CookieConsent` component in `components/CookieConsent.tsx`.
- Integrated functionality to display a cookie consent banner when users visit the site and have not previously consented.
- Utilized `js-cookie` to store user consent in a cookie named `cookieConsent` with an expiration set for one year.
- Enhanced user experience by providing a clear mechanism for users to accept cookies.

### Why This PR?
This PR adds essential functionality to comply with privacy regulations and improve user transparency regarding cookie usage on the website. By implementing a clear consent mechanism, we ensure that users can make informed decisions about their privacy preferences.

### Related Issues
Closes #46

## Summary by CodeRabbit

- **New Features**
  - Added a cookie consent banner to enhance user compliance with cookie laws. Users can now accept the cookie policy directly on the website.

### CODE REVIEW

**Comment by FrancescoXX** [comment]
@devvsakib it shows an error, do you minf trying npm run build locally and fix that ?

image

**Comment by devvsakib** [comment]
yeah sure @FrancescoXX

**Comment by devvsakib** [comment]
@FrancescoXX  done, you can review now☘️

**Comment by devvsakib** [comment]
The deployment failure issue is related to the package-lock.json file. It occurs when someone uses a package management tool other than pnpm. if I'm not wrong!

**Comment by FrancescoXX** [comment]
I have this other error now
image

**Pull request merged**
