### PR TITLE
Chore: Adding CI/CD Workflows and Scripts

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**Adding CI/CD workflows**

Workflows Added: 
1. issue-labeler.yml to label new issues with triage label
2. stale-issue.yml to label issues and PRs stale for 180 days
3. PR.workflow for checking format, lining and type of the code pushed 

Scripts Added:
1. `typecheck` : To check types
2. `format:fix`: To fix the format errors 
3. `format:check`: To check the format errors 

Related To https://github.com/FrancescoXX/rustcrab/issues/24

## Summary by CodeRabbit

- **New Features**
  - Introduced automated issue labeling with a “Triage” label for new issues.
  - Added workflow for marking stale issues and pull requests, with automated closure after inactivity.

- **Chores**
  - Implemented a GitHub Actions workflow for pull requests, including linting, type checking, and building processes.

- **Style**
  - Updated all imports and string literals to use double quotes for consistency.
  - Reformatted HTML, JSX, and CSS attributes for improved readability.

- **Refactor**
  - Revised `package.json` scripts for linting and formatting.
  - Updated Tailwind CSS configuration with consistent double-quote usage and improved theme declarations.

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
Hi @FrancescoXX pls. once have a look into these : )

**Comment by FrancescoXX** [comment]
This branch has conflicts, can you check them? thank you

**Comment by DhairyaMajmudar** [comment]
> This branch has conflicts, can you check them? thank you

I have removed the conflicts : )

**Comment by FrancescoXX** [comment]
thank you. btw we should proceed with issues first. I don't want the whole workflow to start failing and it's hard to test out without merging it

**Comment by DhairyaMajmudar** [comment]
> thank you. btw we should proceed with issues first. I don't want the whole workflow to start failing and it's hard to test out without merging it

Your concern is right, that's why I've tested the workflow in my local fork and they are working as expected.

image

image

**Comment by FrancescoXX** [comment]
closes #40

**Pull request merged**
