### PR TITLE
[issue: #20] : Added a responsive navbar

### PR DESCRIPTION
**Pull request by iharsh02**
https://github.com/user-attachments/assets/78915833-d955-4663-a811-973706889e3c

## Summary by CodeRabbit

- **New Features**
  - Introduced a responsive navigation bar with a hamburger menu for mobile devices.
- **Improvements**
  - Enhanced the `Header` component by incorporating the new `Navbar` for better structure and organization.
  - Updated `SubstackEmbed` component to use a flexible width and improved styling through CSS classes.

### CODE REVIEW

**Comment by iharsh02** [comment]
fixed : #20

**Review by devvsakib — CHANGES_REQUESTED** [review]
Suggestions for better UI: Add the site name with the logo on the left side, and place the GitHub icon in the footer alongside other social links.

Also, just so you know, you are not assigned to this issue. Kindly ask the admin to assign the issue to you before starting to work on it.

**Comment by FrancescoXX** [comment]
@devvsakib is right. we had 2 people working on it before getting assigned.

@iharsh02 please request to be assigned there. and thank you

**Comment by FrancescoXX** [comment]
@iharsh02 can you solve the conflicts, please?

**Comment by iharsh02** [comment]
@FrancescoXX  Done
image

**Comment by FrancescoXX** [comment]
done

**Pull request closed without merging**
