### PR TITLE
[FEATURE] Add "Projects" section #50

### PR DESCRIPTION
**Pull request by nikkbh**
Adds the requested feature - #50 

Here's the screenshot for the developed feature

Light Mode:
image

Dark Mode:
image

## Summary by CodeRabbit

- **New Features**
  - Introduced a "Projects" section to showcase projects with icons, links, and titles in a visually appealing layout.

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
change the AWS n META icon to white in dark mode and increase the size of Meta icon. there are white version also. Please check it out.

**Comment by nikkbh** [comment]
Yeah sure, wasn't able to find good source for the logos, will check official sites

**Comment by nikkbh** [comment]
Added the updates:

Light Mode:
image

Dark Mode:
image

**Review by devvsakib — APPROVED** [review]
lgtm but we have to improve this with slider or something else.

**Pull request merged**
