### PR TITLE
Added X share and solved the conflicts of X

### PR DESCRIPTION
**Pull request by felixoder**
solved the #5 PR's conflicts

## Summary by CodeRabbit

- **New Features**
  - Introduced buttons for copying URL and sharing on Twitter.
  - Added a modal for Twitter sharing.

- **UI Enhancements**
  - Updated text content and styling within the component for a better user experience.

### CODE REVIEW

**Comment by felixoder** [comment]
#98 fix

**Comment by felixoder** [comment]
@FrancescoXX  if you have issues please let me know.

**Comment by FrancescoXX** [comment]
@felixoder , this is not working as intended. When I share the link, it should share a preview; how did you test it?

Also, you made another ?PR,  close the other one if you are using this one rn.


The expected behavior is that by sharing the link, you will see a preview of the post. 

image

image

**Comment by FrancescoXX** [comment]
also, please remove those buttons, this is not how it is intended to work

**Comment by felixoder** [comment]
Got it

**Pull request closed without merging**
