### PR TITLE
#23 Added PR Template to Github Workflow

### PR DESCRIPTION
**Pull request by ranjanport**
This commit consists of a basic required PR Template so that for a Pull Request to be merge some checklists are ensured to maintain a healthy repository.

## Summary by CodeRabbit

- **Chores**
	- Introduced a pull request template to standardize submissions, ensuring key information is provided for every change.

### CODE REVIEW

**Comment by ranjanport** [comment]
@FrancescoXX Could you Verify this PR?

**Comment by FrancescoXX** [comment]
Vercel — Authorization required to deploy.

**Comment by ranjanport** [comment]
> Vercel — Authorization required to deploy.

How Should I do this? @FrancescoXX

**Comment by Vijaykv5** [comment]
> Vercel — Authorization required to deploy.

@FrancescoXX Ig you need to give the authorization to deploy, we actually can't give authorization to vercel as it's hosten on your vercel account.

**Comment by ranjanport** [comment]
> > Vercel — Authorization required to deploy.
> 
> @FrancescoXX Ig you need to give the authorization to deploy, we actually can't give authorization to vercel as it's hosten on your vercel account.

Or It would be great if you just add us to your @vercel team.

**Comment by FrancescoXX** [comment]
image

deployment failed.

try to run npm run build locally
remember to update the project

**Comment by ranjanport** [comment]
> image
> 
> deployment failed.
> 
> try to run npm run build locally remember to update the project

But this doesn’t have any impact to the project source, as this is just a PR template.

**Comment by FrancescoXX** [comment]
have you tried running npm run build on your local machine before pushing?

**Pull request merged**
