### PR TITLE
[FEATURE] add hover effect on social icons

### LINKED ISSUE #77: [FEATURE] add hover effect on social icons
Currently, the social icons at the bottom hav no hover effect

Add a simple one.

It must work both for dark mode ann light mode.

image

### PR DESCRIPTION
**Pull request by soham901**
# Description

added color changing and scaling effect on the social media icons.

Fixes #77 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Test Required (Yes / No)
- No

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

- **Style**
  - Enhanced hover effects for social media icons in the footer for better visual interaction.
  - Adjusted copyright text formatting for improved readability.

- **Refactor**
  - Unified import statements to use double quotes for consistency.

### CODE REVIEW

**Comment by FrancescoXX** [comment]
Thank you but pleas ask it to be assigned first. other 2 people already requested it

**Comment by soham901** [comment]
> Thank you but pleas ask it to be assigned first. other 2 people already requested it

Sorry about that; I'll remember next time

**Comment by FrancescoXX** [comment]
it's o, I will keep this PR for a while in case the other people don't work on it

**Comment by FrancescoXX** [comment]
already done by #77

**Pull request closed without merging**
