### PR TITLE
Issue10 solved Added DSA Section

### PR DESCRIPTION
**Pull request by felixoder**
# Description

Added the DSA Examples

https://github.com/user-attachments/assets/6cae1cf3-4ed4-4099-8165-77db72e008f3

## Summary by CodeRabbit

- **New Features**
  - Introduced a new "DSA Examples" section displaying Rust data structures, with search functionality and modal dialogs for code snippets.
  - Added the ability to copy code snippets to the clipboard.
  - Added "DSA Examples" to the main and mobile navigation menus.

### CODE REVIEW

**Comment by FrancescoXX** [comment]
Thank you for the pr. 

note: there is a bug for this and the other components: they should not redirect to a whole new component that makes the top bar disappear, but just rendered with the new url inside the existing page

but this is consistent with the others so I am gonna merge it

**Comment by felixoder** [comment]
yes! I have noticed! but as you told previously to send PR with one issue so that I thought I will raise an issue over the appearance of the nav and resolve that

**Comment by FrancescoXX** [comment]
yes absolutely one pr per issue.

The navbar looks ok for now, but if you have ideas feel free to elaborate

**Comment by felixoder** [comment]
Yeah, it should be dynamic and may be the sidebar should look appropriate as we are navigating to a page some underline effect of something same gonna happen and the sidebar should be good like sidebar. 

But the issue is assigned to a geek let him solve if there will be a issue I'll raise a pr

**Comment by FrancescoXX** [comment]
yes

**Pull request merged**
